# Generated by Django 3.2.8 on 2022-04-06 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(auto_now=True)),
                ('loan_date_created', models.DateTimeField(auto_now_add=True)),
                ('loan_is_active', models.BooleanField(default=False, null=True)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-loan_date', '-loan_date_created'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_isbn', models.CharField(max_length=20)),
                ('book_edition', models.CharField(max_length=20, null=True)),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.author')),
                ('loan_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.loans')),
                ('publisher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.publisher')),
            ],
        ),
    ]
