# Generated by Django 3.2.8 on 2022-05-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='book_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_isbn',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
